version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/trade-website

permissions:
- object: /
   pattern: "**"
   owner: ec2-user
   group: ec2-user

hooks:
  BeforeInstall:
    - location: bin/install-pkgs
      timeout: 300
      runas: root

  AfterInstall:
    - location: bin/after-install
    timeout: 1200
    runas: root

  ApplicationStop:
   - location: bin/app-stop
     timeout: 10
     runas: ec2-user

  ApplicationStart:
   - location: bin/app-start
     timeout: 60
     runas: ec2-user

  ValidateService:
  - location: validate
    timeout: 60
    runas: ec2-user
